<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>vcl</string>
    <string>vcl.erb</string>
  </array>
  <key>foldingStartMarker</key>
  <string>^.*\b(backend|sub)\s*(\w+\s*)?(\s*\{[^\}]*)?\s*$</string>
  <key>foldingStopMarker</key>
  <string>^\s*\}</string>
  <key>keyEquivalent</key>
  <string>^~V</string>
  <key>name</key>
  <string>VCL</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comment</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#keyword-acl</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#keyword-backend</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#keyword-import</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#keyword-include</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#keyword-sub</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#keywords-others</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#embedded-ruby</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>backend-probe</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\.(url)\s*=</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.other.backend.probe.subkey.vcl</string>
            </dict>
          </dict>
          <key>end</key>
          <string>;</string>
          <key>name</key>
          <string>meta.backend.probe.subkeys.string.vcl</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#strings</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#embedded-ruby</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#embedded-ruby-comment</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>\.(timeout|interval)\s*=</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.other.backend.probe.subkey.vcl</string>
            </dict>
          </dict>
          <key>end</key>
          <string>;</string>
          <key>name</key>
          <string>meta.backend.subkeys.time.vcl</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#time-spec</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>\.(window|threshold)\s*=</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.other.backend.probe.subkey.vcl</string>
            </dict>
          </dict>
          <key>end</key>
          <string>;</string>
          <key>name</key>
          <string>meta.backend.subkeys.number.vcl</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#number-spec</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>backend-subkeys</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\.(host|port)\s*=</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.other.backend.subkey.vcl</string>
            </dict>
          </dict>
          <key>end</key>
          <string>;</string>
          <key>name</key>
          <string>meta.backend.subkeys.string.vcl</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#strings</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#embedded-ruby</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#embedded-ruby-comment</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>\.(probe)\s*=\s*{</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.other.backend.probe.vcl</string>
            </dict>
          </dict>
          <key>end</key>
          <string>}</string>
          <key>name</key>
          <string>meta.backend.probe.vcl</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#backend-probe</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>\.(connect_timeout|first_byte_timeout|between_bytes_timeout)\s*=</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.other.backend.subkey.vcl</string>
            </dict>
          </dict>
          <key>end</key>
          <string>;</string>
          <key>name</key>
          <string>meta.backend.subkeys.time.vcl</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#time-spec</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>\.(max_connections)\s*=</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.other.backend.subkey.vcl</string>
            </dict>
          </dict>
          <key>end</key>
          <string>;</string>
          <key>name</key>
          <string>meta.backend.subkeys.max_connections.vcl</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#number-spec</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>/\*</string>
          <key>end</key>
          <string>\*/</string>
          <key>name</key>
          <string>comment.block.vcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#).*$\n?</string>
          <key>name</key>
          <string>comment.line.vcl</string>
        </dict>
      </array>
    </dict>
    <key>function-invocation</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.vcl</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\b(\S+)\((.*)\)</string>
      <key>name</key>
      <string>meta.control.function</string>
    </dict>
    <key>keyword-acl</key>
    <dict>
      <key>begin</key>
      <string>\b(acl)\s+([a-zA-Z0-9_]+)\s*{</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.other.vcl.acl</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.acl.vcl</string>
        </dict>
      </dict>
      <key>end</key>
      <string>}</string>
      <key>name</key>
      <string>meta.acl.vcl</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#embedded-ruby</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#embedded-ruby-comment</string>
        </dict>
      </array>
    </dict>
    <key>keyword-backend</key>
    <dict>
      <key>begin</key>
      <string>\b(backend)\s+(.*?)\s*{</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.backend.vcl</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.backend.vcl</string>
        </dict>
      </dict>
      <key>end</key>
      <string>}</string>
      <key>name</key>
      <string>meta.backend.vcl</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#backend-subkeys</string>
        </dict>
      </array>
    </dict>
    <key>keyword-import</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.import.vcl</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>string.quoted.double.vcl</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\b(import)\s+([a-zA-Z0-9_]+)</string>
      <key>name</key>
      <string>keyword.import.vcl</string>
    </dict>
    <key>keyword-include</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.include.vcl</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>string.quoted.double.vcl</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\b(include)\s+(["'].+?["'])</string>
      <key>name</key>
      <string>keyword.include.vcl</string>
    </dict>
    <key>keyword-sub</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\b(sub)\s+([a-zA-Z0-9_]+)\s*{</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sub.vcl.action</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.vcl</string>
            </dict>
          </dict>
          <key>end</key>
          <string>}</string>
          <key>name</key>
          <string>meta.sub.vcl</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#sub-body</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>keywords-others</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(director|probe)\b</string>
          <key>name</key>
          <string>keyword.other.vcl</string>
        </dict>
      </array>
    </dict>
    <key>number-spec</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\d</string>
          <key>name</key>
          <string>constant.numeric.vcl</string>
        </dict>
      </array>
    </dict>
    <key>embedded-ruby-comment</key>
    <dict>
      <key>begin</key>
      <string>&lt;%+#</string>
      <key>captures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.comment.erb</string>
        </dict>
      </dict>
      <key>end</key>
      <string>%&gt;</string>
      <key>name</key>
      <string>comment.block.erb</string>
    </dict>
    <key>embedded-ruby</key>
    <dict>
      <key>begin</key>
      <string>&lt;%+(?!&gt;)[-=]?</string>
      <key>captures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.embedded.ruby</string>
        </dict>
      </dict>
      <key>end</key>
      <string>-?%&gt;</string>
      <key>name</key>
      <string>source.ruby.rails.embedded.html</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.ruby</string>
            </dict>
          </dict>
          <key>match</key>
          <string>(#).*?(?=-?%&gt;)</string>
          <key>name</key>
          <string>comment.line.number-sign.ruby</string>
        </dict>
        <dict>
          <key>include</key>
          <string>source.ruby.rails</string>
        </dict>
      </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\{"</string>
          <key>end</key>
          <string>"\}</string>
          <key>name</key>
          <string>string.quoted.double.vcl</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>"</string>
          <key>end</key>
          <string>"</string>
          <key>name</key>
          <string>string.quoted.double.vcl</string>
        </dict>
      </array>
    </dict>
    <key>variables</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(client|server|req|bereq|beresp|obj|resp)\.[a-zA-Z0-9\-\.]+</string>
          <key>name</key>
          <string>variable.global.req.vcl</string>
        </dict>
      </array>
    </dict>
    <key>sub-body</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\{</string>
          <key>end</key>
          <string>\}</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#sub-body</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(call|panic|remove|return|rollback|set|synthetic|unset|purge|error|if|elseif|elsif|else)\b</string>
          <key>name</key>
          <string>keyword.control.vcl.action</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(hash_data|ban|ban_url|regsub|regsuball|std\.log)\b</string>
          <key>name</key>
          <string>support.function.vcl</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#variables</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(true|false|pass|lookup|hit_for_pass|pipe|deliver)\b(?![?!])</string>
          <key>name</key>
          <string>constant.language.vcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b\d+</string>
          <key>name</key>
          <string>constant.numeric.vcl</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#keyword-include</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#embedded-ruby</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#embedded-ruby-comment</string>
        </dict>
      </array>
    </dict>
    <key>time-spec</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\d+\s*(s|ms)</string>
          <key>name</key>
          <string>constant.numeric.time.vcl</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.varnish.vcl</string>
  <key>uuid</key>
  <string>D03975D6-0E30-46EC-9A63-AE75EA409EB9</string>
</dict>
</plist>
