<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>vcl.erb</string>
    <string>vcl</string>
  </array>
  <key>foldingStartMarker</key>
  <string>^.*\b(backend|sub)\s*(\w+\s*)?(\s*\{[^\}]*)?\s*$</string>
  <key>foldingStopMarker</key>
  <string>^\s*\}</string>
  <key>keyEquivalent</key>
  <string>^~V</string>
  <key>name</key>
  <string>VCL</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>\#.*</string>
      <key>name</key>
      <string>comment.line.number-sign.vcl</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\/\/.*</string>
      <key>name</key>
      <string>comment.line.double-slash.vcl</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>\/\*</string>
      <key>end</key>
      <string>\*\/</string>
      <key>name</key>
      <string>comment.block.vcl</string>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.include.vcl</string>
      <key>begin</key>
      <string>\b(import|include)\b\s*</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.import.php</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?=\s|;|$)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.director.vcl</string>
      <key>begin</key>
      <string>(?i)^\s*(director)\s+([a-z0-9_]+)\s+(round\-robin|random|client|hash|dns|fallback)\s*\{</string>
      <key>end</key>
      <string>\}</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.director.vcl</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.type.director.vcl</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>storage.type.director.family.vcl</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.backend.vcl</string>
      <key>begin</key>
      <string>(?i)^\s*(backend)\s+([a-z0-9_]+)\s*\{</string>
      <key>end</key>
      <string>\}</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.backend.vcl</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.type.backend.vcl</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.acl.vcl</string>
      <key>begin</key>
      <string>(?i)^\s*(acl)\s+([a-z0-9_]+)\s*\{</string>
      <key>end</key>
      <string>\}</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.acl.vcl</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.type.acl.vcl</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.probe.vcl</string>
      <key>match</key>
      <string>(?i)^\s*(probe)\s+([a-z0-9_]+)\s*</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.probe.vcl</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.type.probe.vcl</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.subroutine.vcl</string>
      <key>begin</key>
      <string>(?i)^\s*(sub)\s+([a-z0-9_]+)\s*\{</string>
      <key>end</key>
      <string>\}</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.subroutine.vcl</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.type.subroutine.vcl</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>\b(return)\s*\(</string>
      <key>end</key>
      <string>\)</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.vcl</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(deliver_stale|deliver|error|fetch|hash|hit_for_pass|lookup|ok|pass|pipe|restart|synth|retry|abandon|fail|purge)</string>
          <key>name</key>
          <string>constant.language.return.vcl</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.error.vcl</string>
      <key>begin</key>
      <string>\b(error)\b\s*</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.error</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?=\s|;|$)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#strings</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numbers</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(set|unset|remove|synthetic|call|if|else|elsif|else if)\b</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.php</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>include</key>
      <string>#variables</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#numbers</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#strings</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#functions</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#constants</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#subkeys</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#blocks</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>blocks</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\{</string>
          <key>end</key>
          <string>\}</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>subkeys</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>variable.subkey.vcl</string>
          <key>match</key>
          <string>\.(max_connections|first_byte_timeout|between_bytes_timeout|probe|host_header|retries|backend|weight|host|list|port|connect_timeout|ttl|suffix|url|request|window|threshold|initial|expected_response|interval|timeout)\b</string>
        </dict>
      </array>
    </dict>
    <key>constants</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(true|false|now)\b</string>
          <key>name</key>
          <string>constant.builtin.vcl</string>
        </dict>
      </array>
    </dict>
    <key>functions</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(hash_data|regsuball|regsub|ban_url|ban|purge|synth)</string>
          <key>name</key>
          <string>support.function.builtin.vcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>std\.(log|toupper|tolower|set_ip_tos|random|log|syslog|fileread|collect|duration|integer|ip)</string>
          <key>name</key>
          <string>support.function.module.std.vcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>table\.(lookup)</string>
          <key>name</key>
          <string>support.function.module.table.vcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>redis[0-9]?\.(call|send|pipeline|init_redis)</string>
          <key>name</key>
          <string>support.function.module.libvmodredis.vcl</string>
        </dict>
      </array>
    </dict>
    <key>variables</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(req|bereq|obj|beresp|client|server|resp)\.[a-zA-Z0-9\-\_\.]+</string>
          <key>name</key>
          <string>variable.other.vcl</string>
        </dict>
      </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#string-long</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string-single-quoted</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string-double-quoted</string>
        </dict>
      </array>
    </dict>
    <key>numbers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b[0-9]+ ?(m|s|h|d|w)\b</string>
          <key>name</key>
          <string>constant.numeric.time.vcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b[0-9]+(\b|;)</string>
          <key>name</key>
          <string>constant.numeric.vcl</string>
        </dict>
      </array>
    </dict>
    <key>string-long</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>\{"</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.vcl</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>meta.string-contents.quoted.double.vcl</string>
          <key>end</key>
          <string>"\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.vcl</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.long.vcl</string>
        </dict>
      </array>
    </dict>
    <key>string-double-quoted</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>"</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.vcl</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>meta.string-contents.quoted.double.vcl</string>
          <key>end</key>
          <string>"</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.vcl</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.vcl</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>match</key>
              <string>\\[\\"]</string>
              <key>name</key>
              <string>constant.character.escape.vcl</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>string-single-quoted</key>
    <dict>
      <key>begin</key>
      <string>'</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.vcl</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>meta.string-contents.quoted.single.vcl</string>
      <key>end</key>
      <string>'</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.vcl</string>
        </dict>
      </dict>
      <key>name</key>
      <string>string.quoted.single.vcl</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\[\\']</string>
          <key>name</key>
          <string>constant.character.escape.vcl</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.varnish.vcl</string>
  <key>uuid</key>
  <string>D03975D6-0E30-46EC-9A63-AE75EA409EB9</string>
</dict>
</plist>
